### PR TITLE
WMS ID: 4602 updates

### PR DESCRIPTION
**Pull request by chrishoina**
QA testing, updates to intro, manifest, images, md text in labs.

### CODE REVIEW

**Comment by chrishoina** [comment]
I've made the requested changes. I only found one image, but removed the underscore. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Is these images part of your workshop? please create PR with only those files which you are working on and are part of your workshop

image

**Comment by madhusudhanrao-ppm** [comment]
Chris replied to you over the mail.

**Comment by chrishoina** [comment]
> Chris replied to you over the mail.

@madhusudhanrao-ppm or @arabellayao  Can you please review? I think I did this correctly.  I've temporarily removed the offending folder (for WMS 11130). Thanks and sorry for the confusion!

**Comment by chrishoina** [comment]
Mentioning @Brianna-Ambler by request. Thanks!

**Review by Brianna-Ambler — APPROVED** [review]

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
