### PR TITLE
WMS ID 11104, Start Polyglot Development with Autonomous Database

### PR DESCRIPTION
**Pull request by madhusudhanrao-ppm**
WMS ID 11104

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @madhusudhanrao-ppm! There are some images where the root name is visible. Please hide it:

- db-application-development/pythondb-development-oracledb/images/copy-connection.png
- db-application-development/dotnet-development/images/tls-copy.png
- db-application-development/dotnet-development/images/tns-name.png
- db-application-development/adb-with-wallet/images/dns-name.png
- db-application-development/adb-with-wallet/images/tenancy-details.png

**Comment by madhusudhanrao-ppm** [comment]
@ramonamagadan18 - compartment names have been blurred, as per your review

**Review by ramonamagadan18 — APPROVED** [review]

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @madhusudhanrao-ppm . There are some changes:

- db-application-development/adb-with-wallet/images/Screenshot 2024-10-07 at 7.09.35 PM.png : Please hide tenancy name, username, password and change the name to a more appropriate lowercase name;
- db-application-development/adb-with-wallet/images/Screenshot 2024-10-07 at 7.10.21 PM.pn: Please hide the root name and change the name to a more appropriate lowercase name;
-

**Comment by madhusudhanrao-ppm** [comment]
removed screenshots accidentally got it saved in main folder

**Review by ramonamagadan18 — APPROVED** [review]

**Pull request merged**
