### PR TITLE
WMSID: 6742 - Developing Low Code Blockchain Applications using Apex and Blockchain App Builder 

### PR DESCRIPTION
**Pull request by bkvellanki**
Please pull the Oracle Blockchain Platform under developer. orcl-blockchain-platform

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Include the workshop’s WMS ID in the title of the PR
2. Images’ names should be descriptive
3. Make sure all images’ filenames are lower case
4. Delete the howtouse-deletewhenfinished.md when you finish developing
5. Tenancy/manifest.json should use this file as the “Need Help?” Lab: “https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md”
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by bkvellanki** [comment]
Hi - Updated with all the changes suggested except the image names with description. There are really 150+ images, which is very tough at this point to rename all of them. There is very good chance of breaking the labs if we miss one of the names. Will definitely consider it in the next release. Please approve the changes as the approval is in the critical path.

**Comment by bkvellanki** [comment]
Hi - Updated with all the changes suggested except the image names with description. There are really 150+ images, which is very tough at this point to rename all of them. There is very good chance of breaking the labs if we miss one of the names. Will definitely consider it in the next release. Please approve the changes as the approval is in the critical path.


From: Arabella Yao ***@***.***>
Date: Tuesday, August 30, 2022 at 7:48 PM
To: oracle-livelabs/developer ***@***.***>
Cc: Bala Vellanki ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/developer] Oracle Blockchain Platform LiveLab (PR #62)

@arabellayao requested changes on this pull request.

Hi! Please fix the following issues of your PR:

  1.  Include the workshop’s WMS ID in the title of the PR
  2.  Images’ names should be descriptive
  3.  Make sure all images’ filenames are lower case
  4.  Delete the howtouse-deletewhenfinished.md when you finish developing
  5.  Tenancy/manifest.json should use this file as the “Need Help?” Lab: “https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md”<https://urldefense.com/v3/__https:/oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md**B__;4oCd!!ACWV5N9M2RV99hQ!OO8332iJNnyXd35l7O7tcgvXCwIIonp6REeJQdS2SKET4SKtlFiD0U55SwQV02vJKNbkfxJjEx9--DGE-Re3M8DZIwI$>
Please refer to the self QA form<https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx> for details and let me know if you have any questions. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Image names should be self-descriptive required from an accessibility perspective, for example, this image 1-obp-1-3.png can be named as create-compartment.png

image

**Comment by bkvellanki** [comment]
Hi Madhu,

I know what you are saying. We will definitely have another release and we will fix it in that. If we changed the names now there are around 100 + images. We need to update all the instructions. Please approve this as this need to update with other changes by Renee. This is in the critical path for testing

Thanks
Bala
________________________________
From: Madhusudhan Rao ***@***.***>
Sent: Tuesday, August 30, 2022 10:04:47 PM
To: oracle-livelabs/developer ***@***.***>
Cc: Bala Vellanki ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/developer] WMSID: 6742 - Developing Low Code Blockchain Applications using Apex and Blockchain App Builder (PR #62)


Image names should be self-descriptive required from an accessibility perspective, for example, this image 1-obp-1-3.png can be named as create-compartment.png

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/70625227/187583433-60e70cea-1a15-4db3-9ad6-6ab1add8321d.png__;!!ACWV5N9M2RV99hQ!L6UnlXU-1gG18Os4bpAfcKTBNrOmf85NkivnY-lsxANcxHodUOhmgNOpjN4EXxX6Hm4Xu12YM98syOUOqn8ev5IDBvo$>

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
