### PR TITLE
WMSID 4602 updates

### PR DESCRIPTION
**Pull request by chrishoina**
WMSID 4602 updates

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Remove changes to _config.yml from your PR
2. The ocw-freetier/manifest.json and the cow-tenancy/manifest.json have "HEAD" line and "upstream/main" line, and there are two titles for the last lab. Please correct that.
Thanks!

**Comment by chrishoina** [comment]
@arabellayao I think I fixed it. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Remove changes to _config.yml from your PR

image

**Review by chrishoina — COMMENTED** [review]
I've reviewed all.

**Comment by chrishoina** [comment]
I've reviewed and removed the _config.yaml file. I'm not sure what it was for.

**Review by malcherm — APPROVED** [review]

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
