### PR TITLE
python-oracledb LiveLab session #39

### PR DESCRIPTION
**Pull request by veronicadumitriu**
# wms id=440

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
All filenames should be lowercase (including folders, images, files, etc.) 
please refer QA checklist document in WMS

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.
2. Make sure all images’ filenames are lower case
3. All images should have alternative texts in the Markdown files for accessibility
4. workshops/livelabs/manifest.json should use this as the "Need Help" lab: "https://oracle-livelabs.github.io/common/labs/need-help/need-help-livelabs.md" 
4. workshops/ocw-freetier/manifest.json should use this as the "Get Started" lab: "https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md" 
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by arabellayao** [comment]
Hi! I am closing your PR since it is old and behind the oracle main branch. Please open a new PR and fix the suggested change. Thanks!

**Comment by cjbj** [comment]
@arabellayao please don't close PRs like this.  This PR can easily be rebased on main.

**Comment by arabellayao** [comment]
@cjbj 

Closing PRs will not affect anything on your branch. You can always open a new PR. 

We closed the PR since it is been open for several days and behind the main branch, and we did not see any updates on that. Please fix the changes requested and open a new PR.

**Comment by cjbj** [comment]
@arabellayao I understand that, but you still don't need to close PRs since the owner can rebase them on the latest main.  Creating a new PR is just management overhead.  And in busy projects it would be impossible for any PR to always be on the latest main.

**Pull request closed without merging**
