### PR TITLE
WMS ID 11421 Develop with Oracle AI and Database Services: Gen, Vision, Speech, Language, and OML

### PR DESCRIPTION
**Pull request by paulparkinson**
# WMS ID 11421

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [ x] Filenames are descriptive
- [ x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi Paul,

Please make the following updates to your pull request in correspondence with the QA document guidelines

- In the manifest.json the help email should be the stakeholder email address (livelabs-help-devdb-us@oracle.com)
- goals_images folder needs to be moved to under a lab folder in the image folder
- For your workshops/freetier folder, please rename the folder "workshops" and within that folder create a subfolder called "tenancy" where you can put your index and manifest file
- In your manifest.json please update your Get Started and Need Help to use the oracle.livelabs.github.io links referenced in the QA document
- In your setup-oci.md file you have 3 notes back to back. QA guidelines require that you only have up to 1 note per step
- In setup-oci.md please put the "ociconfig-file..." block in a code snippet
- Please indent your numbers throughout the workshop in accordance to QA guidelines
- In your buildapp.md file at the beginning of Task 1 please put "ociconfig-file..." block into a code snippet
- Please make sure all code snippets are indented under numbers throughout the workshop in accordance with QA guidelines
- In oml-healthcare.md under Task 2. Step 5 is typo-ed as step 1 and navigate is misspelled. Toggle is misspelled in step 4

**Comment by paulparkinson** [comment]
Thanks @ZRTalke I've made the changes requested in the latest push: https://github.com/oracle-livelabs/developer/pull/248/commits/88e1b9aa718060e8df03e567b9965f5f9273ad4d

**Comment by ZRTalke** [comment]
Hi @paulparkinson 

It looks like you need to still do the fix of:
"For your workshops/freetier folder, please rename the folder "workshops" and within that folder create a subfolder called "tenancy" where you can put your index and manifest file"

To clarify on this. The folder needs to be named just "workshops" and then within that folder you create another folder named "tenancy" within which you put the index and manifest file

All the other changes look good and I should be able to approve your pull request after this!

Thank you!

**Comment by paulparkinson** [comment]
Thanks @ZRTalke . I'm afraid I'm a little confused.  Isn't that (oracle-ai-for-sustainable-dev/workshops/tenancy/manifest.json) what I have?

Screenshot 2023-12-19 at 8 17 49 PM

**Comment by ZRTalke** [comment]
@paulparkinson 

What I believe I'm seeing on my end is that your workshops folder is literally called "workshops/tenancy" instead of having the structure and name "workshops" (folder inside it)-->"tenancy". In your image this is demonstrated by the fact that you have the folder icon then the name "workshops/tenancy" as compared to an example correct structure also shown in your image of having the folder "vision-genai-sentiment" then it shows your "images" folder a line below as a subfolder in the structure

"tenancy" needs to be a subfolder of "workshops"

**Comment by ZRTalke** [comment]
If you are seeing something different and the correct structure in your actual folder system let me know and send a screenshot please

**Comment by ZRTalke** [comment]
It could be the case that the pull request is just formatting that folder differently due to nothing else being in the workshops folder except the tenancy folder

**Comment by paulparkinson** [comment]
thanks @ZRTalke yes, I think that is the case re "due to nothing else being in the workshops folder except the tenancy folder".  here is my local folder structure
Screenshot 2023-12-20 at 9 52 28 AM

**Comment by ZRTalke** [comment]
My apologies, that one is on me :) 

Approving now

**Review by ZRTalke — APPROVED** [review]

**Comment by paulparkinson** [comment]
@ZRTalke no worries at all and thanks so much! appreciate it and have another ws hot on its trail so I have momentum from your feedback :)

**Pull request merged**
