### PR TITLE
WMS ID: 11120 - Publish ".NET Development with Oracle Autonomous Database Quick Start"

### PR DESCRIPTION
**Pull request by alexkeh**
Created new workshop that is now ready to publish.

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Workshop #11120 in WMS belongs to dotnet-adb-quickstart, but it seems like you are updating files outside of this workshop. Please add the WMS IDs of all workshops that have been updated.
2. The setup.md files should be put under a lab folder.
Thanks!

**Comment by alexkeh** [comment]
All the requested the changes have been made.

**Comment by madhusudhanrao-ppm** [comment]
The folder python-and-database-scripting (and file setup.md) should be inside dotnet-adb-quickstart folder if they are having same WMS ID 11120

image

**Comment by arabellayao** [comment]
Talked to Marion about how to solve issues with this PR 9/9.

**Comment by alexkeh** [comment]
@arabellayao I copied the original setup.md file over the current one. That should revert the python setup.md back to its original contents.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
