### PR TITLE
WMS ID 4602 / 11130

### PR DESCRIPTION
**Pull request by chrishoina**
WMS ID 4602 / 11130 

Updated OCW 2023 manifest.json with Cloudworld support md and file path.

### CODE REVIEW

**Review by anooshapilli — APPROVED** [review]

**Comment by anooshapilli** [comment]
@chrishoina - Please resolve the conflicting files.

**Review by klazarz — APPROVED** [review]

**Comment by klazarz** [comment]
@chrishoina can you check the conflicts please?

**Comment by anooshapilli** [comment]
@chrishoina - Just following up. Please resolve the conflicting files.

**Comment by anooshapilli** [comment]
@chrishoina - Please make the requested changes by tomorrow. As the PR has been open for about a week now, we will close it and you can create a new one when you're ready. Thanks a lot for your understanding!

**Comment by chrishoina** [comment]
I have made these changes and pushed to origin, but I don't see the changes being reflected here. Are you able to see on your end?

**Comment by chrishoina** [comment]
Resubmitting new PRs with changes.

**Pull request closed without merging**
