### PR TITLE
WMS ID 4602 updates

### PR DESCRIPTION
**Pull request by chrishoina**
md changes
image updates 
manifest updates

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

**Review by Brianna-Ambler — CHANGES_REQUESTED** [review]
Hi! 

Just a few changes! They a
[QA.docx](https://github.com/oracle-livelabs/developer/files/9223747/QA.docx)
[QA.docx](https://github.com/oracle-livelabs/developer/files/9223748/QA.docx)
re as follows:

1.  Please remove the numbers from the name of your lab folders.
2. For each objective section in your markdown files, please include the leading line _**In this workshop, you will:**_ .

To ensure your PRs have the best chance at approval, double check your content against the guidelines detailed in our Self QA check list (attached below).

**Review by arabellayao — CHANGES_REQUESTED** [review]
Please resolve merge conflicts on your branch. You can refer to this guide’s Troubleshooting #3 for help: https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/freetier/?lab=4-labs-github-merge-commit-pullrequest#Appendix:TroubleshootingTips

**Review by chrishoina — COMMENTED** [review]
Reviewed all changes.

**Comment by malcherm** [comment]
New PR was created with resolved conflicts.

**Pull request closed without merging**
