### PR TITLE
final adjustments suggested by Anoosha

### PR DESCRIPTION
**Pull request by juarezjuniorgithub**
# Add here your WMS ID
11418

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by juarezjuniorgithub** [comment]
Implemented the final adjustments as suggested by Anoosha Pilli (below):

•	In the introduction lab, please rename Estimated Time to Estimated Workshop Time
•	Indent the images/code blocks/instructions In
Lab 1 
-Task 1 Steps 3, 7, 8, 
-Task 2, Task 5 Steps 4, 5, 6, 
-Task 7 and number the instructions in Task 7. 

Please check and update the same for Lab 3.

•	In lab 2, please move the Understand the Telegram Bot GUI and implementation content as Tasks 1 and 2

•	In Lab 3 Acknowledgements section, please remove the \ after the names

•	The lab titles in manigest.json gile and markdown file need to match. Please update the title in either of the files for all Labs 1, 2, 3, 4

**Review by rahul-tasker — CHANGES_REQUESTED** [review]
Please move the 'springboot-image.png' file into your images directory. Also binary files are not allowed to be stored in github, please request a PAR url to use instead if possible

Screen Shot 2023-08-15 at 1 12 31 PM

**Comment by anooshapilli** [comment]
@juarezjuniorgithub - please resolve the conflicting files issue to review this PR.

**Comment by juarezjuniorgithub** [comment]
@rahul-tasker adjusted per your orientation. The image was left in the wrong directory (an unused one in the backend), apologies for that.  I'll proceed to further request a PAR URL per your orientation as well.
Nevertheless, given the approaching code freeze this Friday (Aug 18), and the importance of providing the best Live Lab content/quality possible, please approve this current PR at your convenience. Thanks a lot for your support!

**Review by ramumg — DISMISSED** [review]
Hi @juarezjuniorgithub, 

I still see that you have conflicts with this PR, we won't be able to approve these changes until that is taken care of. Also I see a file called install.ps1, what type of file is this?
If you are using this livelab for OCW. Please include the need help section in your manifest and then change the Oracle CloudWorlds 2023 - Get Help to  Oracle CloudWorlds 2023 - Support

**Comment by juarezjuniorgithub** [comment]
@ramumg I followed your guidelines, resolved all conflicts and also fixed the manifest sections per your orientation. 
Please approve the PR. Thank you very much for your support!

**Review by rahul-tasker — APPROVED** [review]

**Pull request merged**
