### PR TITLE
implemented the adjustements requested by the livelab team

### PR DESCRIPTION
**Pull request by juarezjuniorgithub**
# Add here your WMS ID
11418

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by bhenndricks — APPROVED** [review]

**Review by anooshapilli — COMMENTED** [review]
@juarezjuniorgithub - Please make these changes to the workshop to approve the PR.
- In the introduction lab, please rename Estimated Time to Estimated Workshop Time
- Indent the images/code blocks/instructions In Lab 1 Task 1 Steps 3, 7, 8, Task 2, Task 5 Steps 4, 5, 6, and number the instructions in Task 7. Please check and update the same for Lab 3.
- In lab 2, please move the Understand the Telegram Bot GUI and implementation content as Tasks 1 and 2
- In Lab 3 Acknowledgements section, please remove the \ after the names
- The lab titles in manigest.json gile and markdown file need to match. Please update the title in either of the files for all Labs 1, 2, 3, 4

**Comment by anooshapilli** [comment]
@juarezjuniorgithub - Just following up on the requested changes. Please resolve the conflicting files

**Comment by anooshapilli** [comment]
@juarezjuniorgithub - Please make the requested changes by tomorrow. As the PR has been open for about a week now, we will close it and you can create a new one when you're ready. Thanks a lot for your understanding!

**Comment by anooshapilli** [comment]
@juarezjuniorgithub - Closing this PR as it has been open for a week now. Please make these changes to the workshop and create a new PR.

- In the introduction lab, please rename Estimated Time to Estimated Workshop Time
- Indent the images/code blocks/instructions In Lab 1 Task 1 Steps 3, 7, 8, Task 2, Task 5 Steps 4, 5, 6, and number the instructions in Task 7. Please check and update the same for Lab 3.
- In lab 2, please move the Understand the Telegram Bot GUI and implementation content as Tasks 1 and 2
- In Lab 3 Acknowledgements section, please remove the \ after the names
- The lab titles in manigest.json gile and markdown file need to match. Please update the title in either of the files for all Labs 1, 2, 3, 4

**Pull request closed without merging**
