### PR TITLE
WMS ID: 11327 - Create a Conversational Interface for your Database with ODA's SQL Dialog

### PR DESCRIPTION
**Pull request by DMTeixeira**
# WMS: 11327

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [ x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by klazarz — APPROVED** [review]

**Review by klazarz — CHANGES_REQUESTED** [review]
@DMTeixeira please update the indext.html and manifest.json to the latest versions. there are URLs in those files pointing to incorrect repositories. Also, please check and resolve any conflicts in your fork

**Comment by anooshapilli** [comment]
@DMTeixeira - Following up on this PR - Please make the requested changes and resolve the conflicting files.

**Comment by anooshapilli** [comment]
Please submit the filled out  [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) once the workshop development is finished to your stakeholder mailbox to review.

**Comment by anooshapilli** [comment]
@DMTeixeira - Once you perform the Self QA of the workshop and make the requested changes, please create a new PR with the changes. Closing this PR for now.

**Pull request closed without merging**
