### PR TITLE
livelab #39 updated as requested by Arabella Yao

### PR DESCRIPTION
**Pull request by veronicadumitriu**
# WMS ID = 440

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by veronicadumitriu** [comment]
@arabellayao - I have created another pull request as per your update

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Include the workshop’s WMS ID in the title of the PR
2. You should not include any zip files in GitHub. Instead, send the zip file to livelabs-help-db_us@oracle.com, and we will upload the file and give you a PAR link
3. Make sure all filenames are lower case
4. All images should have descriptive alternative texts in the Markdown files for accessibility
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Please remove zip file and image names should be lowercase

image

**Comment by veronicadumitriu** [comment]
i have made all the necessary changes - could you please retry with the latest?

**Review by arabellayao — DISMISSED** [review]
1. Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.
2. change Lab-compute-instance folder to lower case
3. freetier/manifest.json should use this as the Need Help lab: "https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md"

**Comment by veronicadumitriu** [comment]
@arabellayao - my branch was up to date with the upstream main at the moment I created the pull request.. not sure how we can overcome these changes but please note that I am only making changes in one folder Python-and-database-scripting so there will be no conflict.

I have implemented the remaining changes as you indicated so if you have a look at it now, I should not be any commit behind. thanks

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
